### ISSUE TITLE
Edit a post [ 3 ]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-pepperjack#16]
Given the logged in user is on the `/my-posts` page
When they select a post's edit button
Then they should be directed to an edit form with that posts's content filled in
And when the form is updated and submitted
Then they should be directed to that post's detail page with the updated information

**Comment by sarahsaturday** [comment]
- "my posts" link in NavBar routes to /my-posts page 
- make sure there is a Posts.js component in Pages (link?)
- edit button routes to edit form (separate page) / update routes
- in PostForm.js add editing functionality
- edit_post function in post_requests.py / imports
- update do_PUT method in request_handler.py / imports
- useEffect in Posts.js for redirecting to that post's individual page (updated)
- submit link/button both creates the post and redirects to the post detail page

**Comment by kelseylemmer** [comment]
I think this needs the create post form....?

**Comment by kelseylemmer** [comment]
client side done
