### ISSUE TITLE
View Current User's Posts [ 3 ]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-pepperjack#17]
Given the logged in user wants to view a list of posts they have created
When they select the "My Posts" link from the navbar
Then they should be taken to `/my-posts` that only shows posts they have authored
And there should be (non-functional) buttons to edit or delete each post

**Comment by sarahsaturday** [comment]
- create "my posts" link in NavBar.js
- create route to /my-posts
- get_post_by_user_id in user_requests.py / imports
- update do_GET in request_handler
- sql query to show only posts by that author (JOIN on user_id)
- edit/delete buttons on each post
- UserPosts.js using Post component to see all user's posts
- fetch call for getUserPosts in UserManagers.js inside Managers directory
