### ISSUE TITLE
Create a Post [ 3 ]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-pepperjack#18]
Given a user selects the "New Post" link in the navbar and are directed to the new post form
When they fill out the form correctly and submit
Then the post should be added and approved
And they should be directed to that post's detail page

**Comment by sarahsaturday** [comment]
- "new post" link in NavBar routes to /newpost page with a form
- make sure there is a Posts.js component in Pages (link?)
- PostForm.js as separate component and import into Posts.js
- Make sure /posts routing exists (link to another issue?)
- create_post function in post_requests.py / imports
- update do_POST method in request_handler.py / imports
- create Post class in Post.py
- useEffect in Posts.js for redirecting to that page's individual page
- create get_single_post in post_requests (/posts/id)
- submit link/button both creates the post and redirects to the post detail page
