### ISSUE TITLE
Create a Tag [ 2 ]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-pepperjack#19]
Given a user is on the tag list page, there should be a create form on the right side of the page
When they fill out the form and submit
Then the tag should be added
And the tag list should update

**Comment by sarahsaturday** [comment]
- Tags.js component in Pages
- TagForm.js as separate component and import into Tags.js
- Make sure /tags routing exists (link to another issue?)
- create_tag function in tag_requests.py / imports
- update do_POST method in request_handler.py / imports
- create Tag class in Tag.py
- useEffect in Tags.js for updating the tags list after form is submitted

**Comment by kelseylemmer** [comment]
Needs to automatically update list without refresh
