### ISSUE TITLE
Create A Category [ 5 ]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-pepperjack#20]
Given a user is on the category list page, there should be a create form on the right side of the page
When they fill out the form and submit
Then the category should be added
And the category list should update

**Comment by sarahsaturday** [comment]
- Categories.js component in Pages
- CategoryForm.js as separate component and import into Categories.js
- Make sure /categories routing exists (link to another issue?)
- create_category function in category_requests.py / imports
- update do_POST method in request_handler.py / imports
- create Category class in Category.py
- useEffect in Categories.js for updating the category list after form is submitted

**Comment by CaseyFerebee** [comment]
handed last step to sarah because of dependency

**Comment by kelseylemmer** [comment]
Needs to automatically update list without refresh
