### ISSUE TITLE
View Tag List [ 3 ]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-pepperjack#21]
Given a user selects the "Tag Management" from the navbar
When they are directed to `/tags`
Then they should see a list of all tags
And tags should be ordered alphabetically
And each tag should have an edit and delete button (functionality for buttons come later)

**Comment by sarahsaturday** [comment]
- Routing for /tags in ApplicationViews
- create edit and delete buttons
- Tag.js component in pages folder
- Create "Tag Management" link div in NavBar.js
- sql query should return sorted list
- create get_all_tags in tag_requests.py / imports
- update do_GET in request _handler.py / imports
