### ISSUE TITLE
View Category List [ 3 ]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-pepperjack#22]
Given a user selects the "Category Management" from the navbar
When they are directed to `/categories`
Then they should see a list of all categories
And categories should be ordered alphabetically
And each category should have an edit and delete button (functionality for buttons come later)

**Comment by sarahsaturday** [comment]
- Routing for /categories in ApplicationViews
- create edit and delete buttons
- Category.js component in pages folder
- Create "Category Management" link div in NavBar.js
- sql query should return sorted list
- create get_all_categories in category_requests.py / imports
- update do_GET in request _handler.py / imports

**Comment by sarahsaturday** [comment]
CLIENT SIDE
- [ ] Routing for /categories in ApplicationViews
- [ ] create edit and delete buttons
- [ ] Category.js component in pages folder
- [ ] Create "Category Management" link div in NavBar.js

SERVER SIDE
- [X] sql query should return sorted list
- [X] create get_all_categories in category_requests.py / imports
- [X] update do_GET in request _handler.py / imports

**Comment by sarahsaturday** [comment]
- [X] Casey made CategoryForm.js and CategoryManager.js
- [X] Casey made /categories route in ApplicationViews but Sarah's element will be different (see: Kennels Client example)
- [ ] To do: useEffect for updating the Category List after someone submits the form to create a new category
