### ISSUE TITLE
View Post Details [ 2 ]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-pepperjack#23]
Given a user is looking at a list of posts
When they click on the post title
Then they should be directed to the post detail page
And the details should include:

- [ ] Title
- [ ] Author's name
- [ ] Category
- [ ] Publication date
- [ ] Content

**Comment by sarahsaturday** [comment]
- Create /post-detail routing
- Make post title clickable
- Create React component for Posts (inside new sub-dir in components)
- get embedded data for each post on server side (test in Postman)
- get_single_post function in post_reqeusts.py / imports
- do_GET method in request_handler.py / imports
- make API call on client side in (new) PostManager.js

**Comment by bhighlander** [comment]
[View Post Details - server](https://github.com/NSS-Day-Cohort-64/rare-python-server-pepperjack/issues/5)

**Comment by bhighlander** [comment]
sql request does not yet join on user to retrieve user's first and last name, will update after front end is implemented
