### ISSUE TITLE
View All Posts [ 3 ]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-pepperjack#24]
Given the user clicks on the "Posts" link in the navbar
When they are directed to the /posts page
Then they should see a list of all posts, with the post title, author name, and category
And the posts should be ordered by the date they were added, most recent first

**Comment by sarahsaturday** [comment]
- "Posts" div exists, need to add route
- Create get_all_posts in post_requests.py / add imports / __init__
- Create do_GET in request_handler.py / add imports
- Create Post class in post.py
- sql query needs to do the sorting by publication_date

**Comment by kelseylemmer** [comment]
pull request for server side posted
