### ISSUE TITLE
Register [ 3 ]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-pepperjack#27]
Given a user has navigated to the register page and wants to create an account
When they submit the form correctly
Then they should be logged in 
And navigated to the home page

**Comment by trobinson1097** [comment]
weight: 1

**Comment by sarahsaturday** [comment]
- Already have register page / functionality on front and back end
- Need to make a class for new user
- Make sure login function is working w/ tokens
- Research token functionality to make sure it's working
- Form already exists but need to test in Postman
- Test in Postman and React
